import type { AntActivity, NestPin, RoleConfig, RoleId, StoreItem } from './types';

export const roleConfigs: Record<RoleId, RoleConfig> = {
  member: {
    id: 'member',
    label: 'Member',
    theme: '#31a866',
    homeMode: 'Explorer koloni',
    headline: 'Jelajahi sarang, ambil misi belanja, dan lihat titik pickup.',
    summary: 'Member melihat gudang, promo, titik pickup, dan jejak aktivitas koloni seperti quest harian.',
    featuredActions: ['Ambil quest belanja', 'Cek pickup', 'Lihat inventory'],
    dashboardLabel: 'Member home',
    primaryModule: 'Belanja & pickup',
    quickStats: [{ label: 'Poin', value: '420' }, { label: 'Order', value: '3' }, { label: 'Pickup', value: '2' }],
    homeCards: [
      { title: 'Paket hari ini', value: '6 item', description: 'Sembako dan produk UMKM siap dibeli.' },
      { title: 'Titik pickup', value: '2 dekat', description: 'Sarang pusat dan Trade Post A aktif.' },
      { title: 'Jejak belanja', value: '12 proof', description: 'Riwayat dummy untuk transparansi nanti.' },
    ],
    menuItems: [
      { label: 'Katalog Koloni', description: 'Lihat item belanja dan paket kebutuhan.' },
      { label: 'Pickup Saya', description: 'Pantau order dan titik ambil.' },
      { label: 'Poin Semut', description: 'Dummy loyalty untuk member.' },
      { label: 'Jejak Belanja', description: 'Cikal bakal proof transaksi.' },
    ],
    storeMode: 'Katalog member dan paket pickup',
    scanMode: 'Scan struk, produk, atau proof belanja',
  },
  surveyor: {
    id: 'surveyor',
    label: 'Surveyor',
    theme: '#44a2ff',
    homeMode: 'Scout lapangan',
    headline: 'Buka kabut peta dan validasi titik UMKM baru.',
    summary: 'Surveyor melihat pin calon UMKM, kunjungan ulang, dan draft validasi sebagai scout mission.',
    featuredActions: ['Buka scout map', 'Tambah titik', 'Ambil lokasi'],
    dashboardLabel: 'Scout board',
    primaryModule: 'Survey UMKM',
    quickStats: [{ label: 'Draft', value: '8' }, { label: 'Ulang', value: '3' }, { label: 'Siap', value: '5' }],
    homeCards: [
      { title: 'Kunjungan prioritas', value: '3 titik', description: 'UMKM butuh foto, GPS, dan kontak.' },
      { title: 'Draft lapangan', value: '8 draft', description: 'Tersimpan lokal sebelum masuk Odoo.' },
      { title: 'Validasi admin', value: '5 siap', description: 'Data sudah lengkap untuk dicek koloni.' },
    ],
    menuItems: [
      { label: 'Form Survey', description: 'Input UMKM, pemilik, produk, dan wilayah.' },
      { label: 'Ambil GPS', description: 'Dummy tombol lokasi untuk field visit.' },
      { label: 'Foto Toko', description: 'Placeholder kamera untuk fase PWA.' },
      { label: 'Export Draft', description: 'Nanti dibuat template Namlah Studio.' },
    ],
    storeMode: 'Referensi produk UMKM hasil survey',
    scanMode: 'Scan barcode produk dan lokasi survey',
  },
  kurir: {
    id: 'kurir',
    label: 'Kurir',
    theme: '#ff8a2f',
    homeMode: 'Runner route',
    headline: 'Kawal jalur suplai dan selesaikan rute pengantaran.',
    summary: 'Kurir melihat rute, pickup, bukti sampai, dan kendala pengiriman sebagai runner mission.',
    featuredActions: ['Ambil pickup', 'Update rute', 'Foto bukti'],
    dashboardLabel: 'Runner route',
    primaryModule: 'Pengiriman',
    quickStats: [{ label: 'Pickup', value: '7' }, { label: 'Jalan', value: '4' }, { label: 'Sampai', value: '11' }],
    homeCards: [
      { title: 'Rute aktif', value: '4 paket', description: 'Urutan pickup dan drop dummy.' },
      { title: 'Bukti sampai', value: '11 foto', description: 'Proof of delivery untuk fase kamera.' },
      { title: 'Kendala', value: '1 warning', description: 'Alamat butuh konfirmasi admin.' },
    ],
    menuItems: [
      { label: 'Ambil Pickup', description: 'Daftar pickup dari gudang/outlet.' },
      { label: 'Rute Hari Ini', description: 'Urutan pengiriman dummy.' },
      { label: 'Foto Bukti', description: 'Placeholder kamera bukti sampai.' },
      { label: 'Kendala Rute', description: 'Catat gagal antar atau alamat salah.' },
    ],
    storeMode: 'Voucher pengiriman dan paket logistik',
    scanMode: 'Scan paket, pickup, dan proof sampai',
  },
  kasir: {
    id: 'kasir',
    label: 'Kasir',
    theme: '#8b72ff',
    homeMode: 'Trade post',
    headline: 'Kelola pos dagang, transaksi, dan stok cepat.',
    summary: 'Kasir melihat antrian transaksi, item laris, dan audit harian seperti trade post HUD.',
    featuredActions: ['Buka trade post', 'Cek stok', 'Tutup shift'],
    dashboardLabel: 'Trade post POS',
    primaryModule: 'Kasir cepat',
    quickStats: [{ label: 'Shift', value: 'Open' }, { label: 'Transaksi', value: '18' }, { label: 'Kas', value: '842K' }],
    homeCards: [
      { title: 'POS cepat', value: '18 trx', description: 'Simulasi transaksi hari ini.' },
      { title: 'Item laris', value: 'Telur', description: 'Produk terjual tertinggi.' },
      { title: 'Tutup shift', value: 'Belum', description: 'Kasir belum tutup laporan harian.' },
    ],
    menuItems: [
      { label: 'Buka POS', description: 'Keranjang transaksi cepat.' },
      { label: 'Scan Produk', description: 'Barcode untuk tambah item.' },
      { label: 'Member Lookup', description: 'Hubungkan Semut-ID pembeli.' },
      { label: 'Tutup Shift', description: 'Rekap kas dan transaksi.' },
    ],
    storeMode: 'Mode POS: item cepat, stok, dan keranjang',
    scanMode: 'Scan barcode produk untuk kasir',
  },
  umkm: {
    id: 'umkm',
    label: 'UMKM',
    theme: '#df5877',
    homeMode: 'Crafting den',
    headline: 'Rawat crafting den produk, stok, dan pesanan.',
    summary: 'UMKM memantau produk aktif, stok, order masuk, dan pembayaran seperti crafting inventory.',
    featuredActions: ['Update stok', 'Craft produk', 'Cek order'],
    dashboardLabel: 'Crafting den',
    primaryModule: 'Produk UMKM',
    quickStats: [{ label: 'Produk', value: '12' }, { label: 'Order', value: '6' }, { label: 'Stok low', value: '2' }],
    homeCards: [
      { title: 'Pesanan masuk', value: '6 order', description: 'Order dummy menunggu konfirmasi.' },
      { title: 'Stok rendah', value: '2 item', description: 'Perlu update kapasitas produksi.' },
      { title: 'Produk aktif', value: '12 SKU', description: 'Katalog yang siap dijual.' },
    ],
    menuItems: [
      { label: 'Produk Saya', description: 'Kelola nama, harga, foto, dan status.' },
      { label: 'Update Stok', description: 'Perbarui jumlah siap jual.' },
      { label: 'Order Masuk', description: 'Konfirmasi pesanan koloni.' },
      { label: 'Pembayaran', description: 'Dummy status pencairan.' },
    ],
    storeMode: 'Etalase produk dan stok UMKM',
    scanMode: 'Scan label produk atau batch produksi',
  },
  admin: {
    id: 'admin',
    label: 'Ratu Semut',
    theme: '#3b7f88',
    homeMode: 'Ruang kendali koloni',
    headline: 'Pantau misi, order, milestone, dan laporan koloni.',
    summary: 'Ratu Semut melihat kesehatan koloni, aktivitas role, validasi misi, dan laporan Odoo ringkas.',
    featuredActions: ['Buka Ratu Semut', 'Lihat sales order', 'Cek laporan'],
    dashboardLabel: 'Ratu Semut',
    primaryModule: 'Ratu Semut',
    quickStats: [{ label: 'Role', value: '41' }, { label: 'Review', value: '9' }, { label: 'Health', value: '86%' }],
    homeCards: [
      { title: 'Validasi pending', value: '9 item', description: 'Role, UMKM, dan produk menunggu cek.' },
      { title: 'Kesehatan sarang', value: '86%', description: 'Dummy index aktivitas koloni.' },
      { title: 'Aktivitas lintas role', value: '41 role', description: 'Ringkasan kerja semua semut.' },
    ],
    menuItems: [
      { label: 'Validasi Role', description: 'Setujui atau tinjau Role-ID.' },
      { label: 'Ratu Semut', description: 'Kanban, sales order, milestone, dan laporan.' },
      { label: 'Audit Jejak', description: 'Proof dummy untuk aktivitas penting.' },
      { label: 'Template Odoo', description: 'Arahkan data ke Namlah Studio.' },
    ],
    storeMode: 'Overview katalog, outlet, dan stok koloni',
    scanMode: 'Scan audit, role, dan bukti aktivitas',
  },
  koperasi: {
    id: 'koperasi',
    label: 'Koperasi',
    theme: '#c3972e',
    homeMode: 'Treasury hall',
    headline: 'Jaga treasury hall, anggota, program, dan SHU dummy.',
    summary: 'Koperasi melihat anggota, simpanan, program, dan transparansi laporan sebagai treasury HUD.',
    featuredActions: ['Cek anggota', 'Lihat SHU', 'Buka rapat'],
    dashboardLabel: 'Treasury hall',
    primaryModule: 'Koperasi',
    quickStats: [{ label: 'Anggota', value: '128' }, { label: 'Program', value: '4' }, { label: 'SHU', value: '2.4M' }],
    homeCards: [
      { title: 'Anggota aktif', value: '128', description: 'Member dummy terhubung ke koloni.' },
      { title: 'Program berjalan', value: '4', description: 'Belanja anggota dan modal usaha.' },
      { title: 'SHU simulasi', value: '2.4M', description: 'Angka dummy untuk transparansi.' },
    ],
    menuItems: [
      { label: 'Daftar Anggota', description: 'Semut-ID anggota koperasi.' },
      { label: 'Program Koperasi', description: 'Belanja, simpanan, dan kegiatan.' },
      { label: 'Rapat & Voting', description: 'Dummy ruang keputusan.' },
      { label: 'Laporan SHU', description: 'Cikal bakal dashboard transparansi.' },
    ],
    storeMode: 'Program belanja anggota dan katalog koperasi',
    scanMode: 'Scan kartu anggota atau bukti program',
  },
};

export const roleOrder: RoleId[] = ['member', 'surveyor', 'kurir', 'kasir', 'umkm', 'admin', 'koperasi'];

export const nestPins: NestPin[] = [
  { id: 'sarang-pusat', type: 'nest', label: 'Queen Hive Kedawung', x: 49, y: 48, status: 'active', activityCount: 42, roles: roleOrder },
  { id: 'umkm-bu-siti', type: 'survey', label: 'Scout Node Bu Siti', x: 26, y: 64, status: 'urgent', activityCount: 7, roles: ['surveyor', 'admin'] },
  { id: 'gudang-sembako', type: 'stock', label: 'Food Vault Sembako', x: 72, y: 34, status: 'active', activityCount: 18, roles: ['member', 'umkm', 'admin', 'koperasi'] },
  { id: 'rute-utara', type: 'route', label: 'Runner Path Utara', x: 63, y: 72, status: 'active', activityCount: 12, roles: ['kurir', 'admin'] },
  { id: 'outlet-a', type: 'store', label: 'Trade Post A', x: 34, y: 30, status: 'calm', activityCount: 9, roles: ['member', 'kasir', 'admin'] },
  { id: 'koperasi', type: 'finance', label: 'Treasury Hall', x: 82, y: 58, status: 'calm', activityCount: 5, roles: ['koperasi', 'admin', 'member'] },
];

export const activities: AntActivity[] = [
  { id: 'a1', roleId: 'member', pinId: 'gudang-sembako', title: 'Paket dapur koloni siap checkout', time: '09:12', severity: 'good' },
  { id: 'a2', roleId: 'surveyor', pinId: 'umkm-bu-siti', title: 'Kunjungan ulang butuh foto produk', time: '09:18', severity: 'warn' },
  { id: 'a3', roleId: 'kurir', pinId: 'rute-utara', title: 'Pickup rute utara menunggu konfirmasi', time: '09:24', severity: 'info' },
  { id: 'a4', roleId: 'kasir', pinId: 'outlet-a', title: 'Outlet A mencatat 18 transaksi pagi', time: '09:31', severity: 'good' },
  { id: 'a5', roleId: 'umkm', pinId: 'gudang-sembako', title: 'Stok keripik perlu update harga', time: '09:36', severity: 'warn' },
  { id: 'a6', roleId: 'admin', pinId: 'sarang-pusat', title: '3 role-ID baru menunggu validasi', time: '09:42', severity: 'info' },
  { id: 'a7', roleId: 'koperasi', pinId: 'koperasi', title: 'Program belanja anggota masuk rekap', time: '09:49', severity: 'good' },
];

export const storeItems: StoreItem[] = [
  { id: 'beras', title: 'Beras Koloni 5kg', category: 'Sembako', price: 'Rp68.000', stock: '32 sak' },
  { id: 'telur', title: 'Telur Ayam Lokal', category: 'Dapur', price: 'Rp29.000', stock: '18 kg' },
  { id: 'sayur', title: 'Paket Sayur Pagi', category: 'Segar', price: 'Rp22.000', stock: '44 paket' },
  { id: 'kopi', title: 'Kopi UMKM Cirebon', category: 'UMKM', price: 'Rp38.000', stock: '21 pouch' },
  { id: 'kurir', title: 'Voucher Kurir Koloni', category: 'Layanan', price: 'Rp8.000', stock: 'aktif' },
  { id: 'shu', title: 'Program Belanja Anggota', category: 'Koperasi', price: 'Dummy', stock: 'pilot' },
];
