import type { RoleConfig, RoleId } from './types';

export const roleConfigs: Record<RoleId, RoleConfig> = {
  member: {
    id: 'member',
    label: 'Member',
    theme: '#31a866',
    homeMode: 'Belanja koloni',
    headline: 'Belanja, pickup, dan bukti kerja mengikuti task Odoo koloni.',
    summary: 'Member melihat order belanja, pickup, dan bukti aktivitas yang ditarik dari project/task Odoo.',
    featuredActions: ['Buat order belanja', 'Pantau pickup', 'Kirim bukti'],
    dashboardLabel: 'Member home',
    primaryModule: 'Belanja & pickup',
    quickStats: [{ label: 'Task', value: '-' }, { label: 'Order', value: '-' }, { label: 'Pickup', value: '-' }],
    homeCards: [
      { title: 'Order belanja', value: 'Odoo', description: 'Order dibuat lewat template belanja koloni.' },
      { title: 'Pickup', value: 'Odoo', description: 'Pickup mengikuti task pengiriman.' },
      { title: 'Bukti', value: 'Odoo', description: 'Bukti tersimpan di task terkait.' },
    ],
    menuItems: [
      { label: 'Belanja Koloni', description: 'Aktifkan template belanja untuk koloni.' },
      { label: 'Pickup Saya', description: 'Pantau task pickup dari Odoo.' },
      { label: 'Bukti Belanja', description: 'Kirim bukti ke task yang benar.' },
      { label: 'Riwayat Order', description: 'Baca sale.order yang terhubung.' },
    ],
    storeMode: 'Order belanja koloni',
    scanMode: 'Scan struk, produk, atau bukti belanja',
  },
  surveyor: {
    id: 'surveyor',
    label: 'Surveyor',
    theme: '#44a2ff',
    homeMode: 'Survey lapangan',
    headline: 'Validasi lokasi dan kontak UMKM melalui task Odoo.',
    summary: 'Surveyor mengisi bukti lokasi, foto, dan catatan ke project.task yang ditugaskan.',
    featuredActions: ['Buka task survey', 'Tambah lokasi', 'Kirim bukti'],
    dashboardLabel: 'Survey board',
    primaryModule: 'Survey UMKM',
    quickStats: [{ label: 'Task', value: '-' }, { label: 'Lokasi', value: '-' }, { label: 'Bukti', value: '-' }],
    homeCards: [
      { title: 'Task survey', value: 'Odoo', description: 'Daftar tugas survey berasal dari project.task.' },
      { title: 'Kontak lokasi', value: 'Odoo', description: 'Kontak owner disimpan sebagai partner/task.' },
      { title: 'Validasi', value: 'Odoo', description: 'Ratu Koloni memeriksa bukti di stage validasi.' },
    ],
    menuItems: [
      { label: 'Form Survey', description: 'Isi UMKM, pemilik, produk, dan wilayah.' },
      { label: 'Ambil GPS', description: 'Simpan titik lokasi pada bukti task.' },
      { label: 'Foto Toko', description: 'Lampirkan bukti foto ke task.' },
      { label: 'Kirim Validasi', description: 'Majukan task ke stage validasi.' },
    ],
    storeMode: 'Survey dan validasi UMKM',
    scanMode: 'Scan barcode produk dan lokasi survey',
  },
  kurir: {
    id: 'kurir',
    label: 'Kurir',
    theme: '#ff8a2f',
    homeMode: 'Rute pengiriman',
    headline: 'Pickup dan pengiriman berjalan dari task koloni yang sama.',
    summary: 'Kurir menangani pickup, pengiriman, bukti sampai, dan kendala dari task Odoo.',
    featuredActions: ['Ambil pickup', 'Update rute', 'Foto bukti'],
    dashboardLabel: 'Runner route',
    primaryModule: 'Pengiriman',
    quickStats: [{ label: 'Pickup', value: '-' }, { label: 'Jalan', value: '-' }, { label: 'Sampai', value: '-' }],
    homeCards: [
      { title: 'Pickup', value: 'Odoo', description: 'Pickup dibuat oleh template pengiriman.' },
      { title: 'Bukti sampai', value: 'Odoo', description: 'Proof of delivery masuk ke task kurir.' },
      { title: 'Kendala', value: 'Odoo', description: 'Catatan kendala ditempel ke task.' },
    ],
    menuItems: [
      { label: 'Ambil Pickup', description: 'Buka task pickup dari Odoo.' },
      { label: 'Rute Hari Ini', description: 'Urutan pengiriman dari task aktif.' },
      { label: 'Foto Bukti', description: 'Upload bukti sampai ke task.' },
      { label: 'Kendala Rute', description: 'Catat gagal antar atau alamat salah.' },
    ],
    storeMode: 'Task pickup dan delivery',
    scanMode: 'Scan paket, pickup, dan bukti sampai',
  },
  kasir: {
    id: 'kasir',
    label: 'Kasir',
    theme: '#8b72ff',
    homeMode: 'POS koloni',
    headline: 'Transaksi kasir wajib menjadi sale.order yang terikat task kasir.',
    summary: 'Kasir membuat sale.order dengan customer koloni dan kontak kirim sesuai input transaksi.',
    featuredActions: ['Buka POS', 'Cek task kasir', 'Tutup shift'],
    dashboardLabel: 'Trade post POS',
    primaryModule: 'Kasir cepat',
    quickStats: [{ label: 'Shift', value: '-' }, { label: 'Order', value: '-' }, { label: 'Kas', value: '-' }],
    homeCards: [
      { title: 'POS cepat', value: 'Odoo', description: 'Transaksi ditulis ke sale.order.' },
      { title: 'Task kasir', value: 'Odoo', description: 'Satu Semut-ID kasir memiliki satu task induk.' },
      { title: 'Pengiriman', value: 'Odoo', description: 'Kontak kirim menjadi partner_shipping_id.' },
    ],
    menuItems: [
      { label: 'Buka POS', description: 'Buat sale.order transaksi kasir.' },
      { label: 'Kontak Kirim', description: 'Isi penerima pengiriman transaksi.' },
      { label: 'Task Kasir', description: 'Pantau smart link transaksi pada task.' },
      { label: 'Tutup Shift', description: 'Rekap kas dan transaksi dari Odoo.' },
    ],
    storeMode: 'POS sale.order kasir',
    scanMode: 'Scan barcode produk untuk kasir',
  },
  umkm: {
    id: 'umkm',
    label: 'UMKM',
    theme: '#df5877',
    homeMode: 'Produk UMKM',
    headline: 'Produk, stok, dan order mengikuti template project UMKM.',
    summary: 'UMKM mengurus onboarding, produk, stok, dan order melalui project/task Odoo.',
    featuredActions: ['Update stok', 'Kelola produk', 'Cek order'],
    dashboardLabel: 'UMKM board',
    primaryModule: 'Produk UMKM',
    quickStats: [{ label: 'Produk', value: '-' }, { label: 'Order', value: '-' }, { label: 'Stok', value: '-' }],
    homeCards: [
      { title: 'Order masuk', value: 'Odoo', description: 'Order dibaca dari sale.order.' },
      { title: 'Stok', value: 'Odoo', description: 'Stok harus berasal dari data produk.' },
      { title: 'Produk aktif', value: 'Odoo', description: 'Produk siap jual mengikuti stage validasi.' },
    ],
    menuItems: [
      { label: 'Produk Saya', description: 'Kelola produk, harga, foto, dan status.' },
      { label: 'Update Stok', description: 'Perbarui jumlah siap jual.' },
      { label: 'Order Masuk', description: 'Konfirmasi pesanan koloni.' },
      { label: 'Pembayaran', description: 'Pantau transaksi yang terkait.' },
    ],
    storeMode: 'Etalase produk dan stok UMKM',
    scanMode: 'Scan label produk atau batch produksi',
  },
  admin: {
    id: 'admin',
    label: 'Ratu Semut',
    theme: '#3b7f88',
    homeMode: 'Ruang kendali koloni',
    headline: 'Pantau project, task, sale.order, milestone, dan laporan koloni.',
    summary: 'Ratu Semut membaca data Odoo live sesuai project dan koloni yang ia kelola.',
    featuredActions: ['Buka Ratu Semut', 'Lihat sale.order', 'Cek laporan'],
    dashboardLabel: 'Ratu Semut',
    primaryModule: 'Ratu Semut',
    quickStats: [{ label: 'Role', value: '-' }, { label: 'Review', value: '-' }, { label: 'Health', value: '-' }],
    homeCards: [
      { title: 'Validasi pending', value: 'Odoo', description: 'Role, UMKM, dan produk menunggu cek.' },
      { title: 'Kesehatan koloni', value: 'Odoo', description: 'Aktivitas dibaca dari task dan order.' },
      { title: 'Lintas role', value: 'Odoo', description: 'Ringkasan kerja semua role koloni.' },
    ],
    menuItems: [
      { label: 'Validasi Role', description: 'Setujui atau tinjau Role-ID.' },
      { label: 'Ratu Semut', description: 'Kanban, sale.order, milestone, dan laporan.' },
      { label: 'Audit Jejak', description: 'Proof aktivitas penting.' },
      { label: 'Template Odoo', description: 'Aktifkan project template koloni.' },
    ],
    storeMode: 'Overview katalog, outlet, dan stok koloni',
    scanMode: 'Scan audit, role, dan bukti aktivitas',
  },
  koperasi: {
    id: 'koperasi',
    label: 'Koperasi',
    theme: '#c3972e',
    homeMode: 'Program koloni',
    headline: 'Program anggota dan laporan berjalan dari project koloni.',
    summary: 'Koperasi melihat program, anggota, dan transparansi laporan melalui project/task Odoo.',
    featuredActions: ['Cek anggota', 'Lihat laporan', 'Buka program'],
    dashboardLabel: 'Koperasi',
    primaryModule: 'Koperasi',
    quickStats: [{ label: 'Anggota', value: '-' }, { label: 'Program', value: '-' }, { label: 'Laporan', value: '-' }],
    homeCards: [
      { title: 'Anggota aktif', value: 'Odoo', description: 'Anggota berasal dari portal user/partner.' },
      { title: 'Program berjalan', value: 'Odoo', description: 'Program dibuat dari project template.' },
      { title: 'Laporan', value: 'Odoo', description: 'Angka dibaca dari jurnal dan order.' },
    ],
    menuItems: [
      { label: 'Daftar Anggota', description: 'Semut-ID anggota koperasi.' },
      { label: 'Program Koperasi', description: 'Belanja, simpanan, dan kegiatan.' },
      { label: 'Rapat & Voting', description: 'Ruang keputusan koloni.' },
      { label: 'Laporan', description: 'Dashboard transparansi dari Odoo.' },
    ],
    storeMode: 'Program belanja anggota',
    scanMode: 'Scan kartu anggota atau bukti program',
  },
};

export const roleOrder: RoleId[] = ['member', 'surveyor', 'kurir', 'kasir', 'umkm', 'admin', 'koperasi'];
